name: snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: DivaQueen-dev
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=FF69B4
            dist/github-contribution-grid-snake-dark.svg?color_snake=FF69B4&color_dots=#2b2b2b,#3a3a3a,#4a4a4a,#FF69B4,#FF1493
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
