name: generate snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: DivaQueen-dev
          outputs: |
            github-contribution-grid-snake.svg?color_snake=8A7CFF&color_dots=#1a1b27,#3b2f5c,#6c63ff,#a084ff,#f78da7
            github-contribution-grid-snake-dark.svg?color_snake=ff79c6&color_dots=#1a1b27,#2a2139,#6c63ff,#a084ff,#ff79c6

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
